apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ .Values.werf.name }}
spec:
  backendType: secretsManager
  region: us-east-2
  dataFrom:
    - {{ .Values.werf.env }}/bl-network/{{ .Values.werf.name }}
